language: ruby
rvm:
  - 2.6.0

sudo: false

install: bundle install --jobs=3 --retry=3
script: jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: ./out
  on:
    branch: master
