# Site settings
title: "Learning Locker Documentation"
email: "hello@learninglocker.net"
description: "Documentation for Learning Locker, the open source learning record store."
source: "./src"
destination: "./out"

# Build settings
markdown: kramdown
permalink: pretty

# Plugins
plugins:
  - jekyll-redirect-from

# YAML Frontmatter variables
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"

