# Site settings
title: "Learning Locker Documentation"
email: "hello@learninglocker.net"
description: "Documentation for Learning Locker, the open source learning record store."
baseurl: "/docs"
url: "http://learninglocker.net"
exclude: 
  - "readme.md"
  - "contributing.md"

# Build settings
markdown: kramdown
permalink: pretty

# YAML Frontmatter variables
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
